[package]
name = "autobench"
version = "0.1.0"
edition = "2025"

[dependencies]
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.0", features = ["derive"] }
